apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mynew-app
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: web-cool
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx-container
          image: nginx
  
  replicas: 5

  selector:
    matchLabels:
      app: front-end