apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-newdeploy
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: web-cool
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
  
  replicas: 5

  selector:
    matchLabels:
      app: front-end