apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollout-update
spec:
  replicas: 10
  minReadySeconds: 45
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  selector:
    matchLabels:
      role: app
  template:
    metadata:
      labels:
        role: app
    spec:
      containers:
        - name: Update-container
          image: nginx:1.18
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443